#!/usr/bin/env python

import io
import json
import os.path
import sys
import time
import paho.mqtt.client as mqtt
import paho.mqtt.publish as publish
from argparse import ArgumentParser


# ----------------------------------------------------------------------
# MQTT home-assistant auto-discovery
# ----------------------------------------------------------------------

def send_discovery_configs(config):
    send_ambilite_discovery(config)
    send_settopbox_discovery(config)
    send_playstation4_discovery(config)

def send_ambilite_discovery(config):
    topic = "%s/config" % config["ambilite_base_topic"]
    #send_payload(topic, "", config)
    send_payload(topic, json.dumps({
        "unique_id": config["unique_id"],
        "name": config["name"],
        "state_topic": "%s/state" % config["ambilite_base_topic"],
        "command_topic": "%s/set" % config["ambilite_base_topic"],
        "json_attributes_topic": "%s/attributes" % config["ambilite_base_topic"],
        "optimistic": "false",
        "retain": "true",
        "icon": "mdi:shape-rectangle-plus",
        "device": {
            "identifiers": [config["unique_id"]],
            "manufacturer": "Maurice Makaay",
            "model": "Raspberry Ambilite",
            "sw_version": config["version"],
            "name": "Ambilite"
        }
    }), config)

def send_settopbox_discovery(config):
    topic = "%s/config" % config["stb_base_topic"]
    #send_payload(topic, "", config)
    send_payload(topic, json.dumps({
        "unique_id": config["unique_id"] + "-stb",
        "name": "settopbox",
        "state_topic": "%s/state" % config["stb_base_topic"],
        "command_topic": "%s/set" % config["stb_base_topic"],
        "json_attributes_topic": "%s/attributes" % config["stb_base_topic"],
        "optimistic": "false",
        "retain": "true",
        "icon": "mdi:set-top-box",
        "device": {
            "identifiers": [config["unique_id"] + "-stb"],
            "manufacturer": "Maurice Makaay",
            "model": "Raspberry",
            "sw_version": config["version"],
            "name": "Settopbox watcher"
        }
    }), config)

def send_playstation4_discovery(config):
    topic = "%s/config" % config["ps4_base_topic"]
    #send_payload(topic, "", config)
    send_payload(topic, json.dumps({
        "unique_id": config["unique_id"] + "-ps4",
        "name": "playstation4",
        "state_topic": "%s/state" % config["ps4_base_topic"],
        "command_topic": "%s/set" % config["ps4_base_topic"],
        "optimistic": "false",
        "retain": "true",
        "icon": "mdi:playstation",
        "device": {
            "identifiers": [config["unique_id"] + "-ps4"],
            "manufacturer": "Maurice Makaay",
            "model": "Raspberry",
            "sw_version": config["version"],
            "name": "Playstation watcher"
        }
    }), config)

def send_attributes(state, config):
    topic = "%s/attributes" % config["ambilite_base_topic"],
    send_payload(topic, json.dumps(state["attributes"]), config)

def send_state(state, config):
    topic = "%s/state" % config["ambilite_base_topic"],
    send_payload(topic, "ON" if state["enabled"] else "OFF", config)

def send_payload(topic, payload, config):
    verbose("Publish: %s: %s" % (topic, payload))

    publish.single(
        topic, payload,
        hostname=config["broker"],
        auth = {
            "username": config["username"],
            "password": config["password"]
        })


# ----------------------------------------------------------------------
# MQTT subscription
# ----------------------------------------------------------------------

def start_subscription_loop(state, config): 
    """Create an MQTT subscriber to handle incoming messages and
       start a listen loop in a separate thread to handle these
       messages."""
    client = mqtt.Client(config["unique_id"])
    client.config = config
    client.state = state
    client.username_pw_set(
        username=config["username"],
        password=config["password"])
    client.on_connect = on_connect
    client.on_disconnect = on_disconnect
    client.on_message = on_message
    client.connect(config["broker"])
    client.subscribe("%s/set" % config["ambilite_base_topic"], qos=0)
    client.subscribe("%s/snapshot" % config["ambilite_base_topic"], qos=0)
    client.loop_start()

def on_connect(client, userdata, flags, rc):
    if rc == 0:
        print("Subscriber: Connected to broker")
        send_discovery_configs(client.config)
        send_state(client.state, client.config)
    else:
        print("Subscriber: Connecting to broker failed (rc = %d)" % rc)

def on_disconnect(client, userdata, rc):
    if rc == 0:
        print("Subscriber: Disconnected from broker")
    else:
        print("Subscriber: Unexpected disconnected from broker (rc = %d)" % rc)

def on_message(client, userdata, message):
    verbose("Subscriber: Incoming message: %s" % message.topic)
    try:
        if message.topic.endswith("/snapshot"):
            client.state["store_snapshots"] = True
            print("Subscriber: Scheduled storing of snapshot")
        elif message.topic.endswith("/set"):
            on_or_off = str(message.payload.decode("utf-8"))
            if on_or_off == 'ON':
                client.state["enabled"] = True
                fh = open(client.config["state_file"], "w")
                fh.write("Ambilite turned on at %f" % time.time())
                fh.close()
                print("Subscriber: Ambilite turned on")
            else:
                client.state["enabled"] = False
                if os.path.exists(client.config["state_file"]):
                    os.unlink(client.config["state_file"])
                print("Subscriber: Ambilite turned off")
            send_state(client.state, client.config)
    except Exception as e:
        print("Subscriber: Failed to set ambilite state: %s: %s" % (type(e).__name__, str(e)))


# ----------------------------------------------------------------------
# MQTT publishing
# ----------------------------------------------------------------------

import numpy as np
import numexpr as ne
import picamera
import picamera.array
from PIL import Image, ImageDraw, ImageFont


def start_publish_loop(state, config):
    with picamera.PiCamera() as cam:
        while True:
            try:
                make_snapshot = state["store_snapshots"]
                state["store_snapshots"] = False
                if state["enabled"]:
                    handle_ambilite(cam, config, make_snapshot)
                handle_settopbox(cam, config, make_snapshot)
            except Exception as e:
                verbose("Publish: Unhandled exception: %s: %s" % (type(e).__name__, str(e)))
                time.sleep(1) # prevent tight error loops


def store_snapshot(config, img, name):
    swap = "%s/snapshot_%s.swap.jpg" % (config["snapshot_path"], name)
    final = "%s/snapshot_%s.jpg" % (config["snapshot_path"], name)
    Image.fromarray(img).save(swap)
    os.rename(swap, final)
    print("Publish: stored %s snapshot: %s" % (name, final))

def handle_settopbox(cam, config, make_snapshot):
    cam.zoom = (0.50, 0.59, 0.10, 0.10)
    cam.resolution = (736, 480)
    cam.awb_mode = 'fluorescent'
    cam.meter_mode = 'average'
    cam.saturation = 100
    cam.contrast = 100

    with picamera.array.PiRGBArray(cam) as store:
        cam.capture(store, format="rgb")
        img = store.array
        stb, ps4 = get_device_status(img)
        print("Device status: settopbox=%s, playstation4=%s" % (stb, ps4))

        # Publish screen snapshot to file.
        if make_snapshot:
            store_snapshot(config, img, "settopbox")
         
        # Publish state via MQTT.
        send_payload("%s/state" % config["stb_base_topic"], stb, config)
        send_payload("%s/state" % config["ps4_base_topic"], ps4, config)

SETTOPBOX_LED = {
    'R': 'OFF',
    'G': 'ON'
}

PLAYSTATION4_LED = {
    'R': 'OFF',
    'RGB': 'ON'
}

def get_device_status(img):
    CUTOFF = 100

    states = []
    state = '-'
    for line in img:
        if np.all(line <= CUTOFF):
            new_state = '-';
        else:
            rMax = np.max(line[::, 0])
            gMax = np.max(line[::, 1])
            bMax = np.max(line[::, 2])
            new_state = (
               ('R' if rMax > CUTOFF else '') +
               ('G' if gMax > CUTOFF else '') +
               ('B' if bMax > CUTOFF else '')
            )
        if new_state != state:
            if new_state == '-':
                states.append(new_state)
                state = new_state
            elif state == '-':
                states.append(new_state)
                state = new_state
            elif len(new_state) > len(state):
                states[-1] = new_state
                state = new_state

    states = [s for s in states if s != '-']

    if len(states) != 2:
        return ('UNKNOWN', 'UNKNOWN')
    stb, ps4 = states
    if stb in SETTOPBOX_LED and ps4 in PLAYSTATION4_LED:
        return (SETTOPBOX_LED[stb], PLAYSTATION4_LED[ps4])
    return ('UNKNOWN', 'UNKNOWN')

def handle_ambilite(cam, config, make_snapshot):
    """Take a shot of the tv screen, compute the dominant color and
       pushlish the color to Home Assistant."""
    cam.zoom = (0.48, 0.20, 0.305, 0.255)
    cam.resolution = (736, 480)
    cam.awb_mode = 'fluorescent'
    cam.meter_mode = 'backlit'
    cam.saturation = 0
    cam.contrast = 0

    with picamera.array.PiRGBArray(cam) as store:
        cam.capture(store, format="rgb")  
        img = store.array
        #img = img[:, :, ::-1]

        # Publish screen snapshot to file.
        if make_snapshot:
            store_snapshot(config, img, "television")

        dominant_color = get_dominant_color(img)

    set_color_in_state(dominant_color, config, state)
    send_attributes(state, config)
    send_state(state, config)

def get_dominant_color(img):
    SAMPLE_STEP = 20
    POSTERIZE = 25
    LOW = 50
    HIGH = 220
    TOP_SCREEN_CUTOFF = 0.8

    # To save time in the following steps, take a sample of the
    # total amount of items. For our case (determining the dominant
    # color for an ambilight-like setup, this is good enough).
    #
    # The bottom of the screen normally is not that interesting for
    # the single color ambilight setup that I'm going for, so
    # that's why I go for a top section only here.
    height = int(img.shape[0] * TOP_SCREEN_CUTOFF)
    downsampled = img[0:height:SAMPLE_STEP, 0::SAMPLE_STEP]

    # Create a copy to reduce colors further, so we can later on
    # come back to the downsampled image.
    reduced = downsampled.copy()

    # Pull all items that are too dark or too light to (0, 0, 0).
    #extremes = (reduced < LOW) & (reduced > HIGH)
    #extremes = 0
    reduced[np.all(reduced < LOW, axis=-1)] = 0
    reduced[np.all(reduced > HIGH, axis=-1)] = 0

    # Reduce the number of colors in the image, by grouping them
    # in bins. When we have a lot of slightly different colors in the image,
    # this will group those colors into a single group, making all of the
    # colors count for finding a good dominant color.
    reduced = reduced // POSTERIZE * POSTERIZE

    # Pull all items that are now too dark or too light to (0, 0, 0).
    reduced[np.all(reduced < LOW, axis=-1)] = 0
    reduced[np.all(reduced > HIGH, axis=-1)] = 0

    # Find the dominant color bin that is not (0, 0, 0)..
    # For this, first convert the x, y, (r, g, b) dimensions into a
    # list of (r, g, b) items.
    flat = reduced.reshape(-1, 3)

    # Filter out the items that are (0, 0, 0).
    flat = flat[np.all(flat != (0, 0, 0), -1)]

    # No items left?
    if not len(flat):
        return (0, 0, 0)

    # Convert the (r, g, b) values into a single integer value.
    col_range = (256, 256, 256)
    eval_params = {
        'R': flat[:,0],
        'G': flat[:,1],
        'B': flat[:,2],
        'Rmax': col_range[0],
        'Gmax': col_range[1]
    }
    rgb_values = ne.evaluate('R*Rmax*Gmax + G*Gmax + B', eval_params)

    # Find the dominant RGB integer value.
    dominant = np.bincount(rgb_values).argmax()

    # Reverse engineer this value into an (r, g, b) array.
    bin_rgb = np.unravel_index(dominant, col_range)

    # Find the original image colors that fall in this bin.
    use = downsampled[np.all(reduced == bin_rgb, 2)]

    # Compute the average color from the original colors.
    average_rgb = tuple(int(d) for d in np.average(use, 0))

    return average_rgb

def set_color_in_state(color, config, state):
    state["attributes"]["r"] = color[0]
    state["attributes"]["g"] = color[1]
    state["attributes"]["b"] = color[2]

# ----------------------------------------------------------------------
# Main
# ----------------------------------------------------------------------

# I know, my home automation MQTT password  can be found in this file.
# No worries. It's my dev host and it is not accessible from the internet.
# This will be moved to a configuration file for the final version.

config = {
    "version": "1.0.0",
    "broker": "172.17.206.1",
    "username": "hass",
    "password": "burgers",
    "state_file": "/var/run/ambilite.active",
    "snapshot_path": "/var/www/html",
    "ambilite_base_topic": "homeassistant/switch/ambilite",
    "stb_base_topic": "homeassistant/switch/settopbox",
    "ps4_base_topic": "homeassistant/switch/playstation4",
    "unique_id": "ambilite-mediacontroller",
    "name": "ambilite",
}

state = {
    "enabled": os.path.exists(config["state_file"]),
    "store_snapshots": True,
    "attributes": {}
}

p = ArgumentParser(description="Look at the tv")
p.add_argument(
    "-v", "--verbose",
    default=False, action="store_true",
    help="enable verbose output (default: disabled)")
args = p.parse_args()

if args.verbose:
    def verbose(msg):
        print(msg)
else:
    def verbose(msg):
        pass

set_color_in_state((100, 100, 100), config, state)
start_subscription_loop(state, config)
start_publish_loop(state, config)

