#!/bin/bash

mosquitto_pub \
    -h hass.home.makaay.nl -p 1883 \
    -u hass -P burgers \
    -t homeassistant/switch/ambilite/state \
    -m 'ON'

mosquitto_pub \
    -h hass.home.makaay.nl -p 1883 \
    -u hass -P burgers \
    -t homeassistant/switch/ambilite/attributes \
    -m '{"state": "ON", "r": 100, "g":212, "b":99}'
